### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KilopaNye**
老師您好，我是伯韋。目前已完成第二周第一版作業，再請您審閱，謝謝。
http://3.114.143.152:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your webpage will load unrelated attractions after searching `北`.
2. Your webpage never render attractions in the last page.
3. Fill MRT name in search input box after clicking on it.

**Comment by KilopaNye** [comment]
老師不好意思，早上睡茫按錯，太早重新發出重新請求，目前已更改好上述反饋內容，再請老師審閱，謝謝老師。
http://3.114.143.152:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

It will be better if you use proportional width for your attraction blocks in the middle and small devices.

**Comment by KilopaNye** [comment]
謝謝老師的建議!

**Pull request merged**
